### ISSUE TITLE
Elasticsearch ^5.0.0

### ISSUE THREAD

**Issue by amartin916** [homeaway/kibana#1]
When I try to install the nestedSupport-4.x branch, it tells me that I need to have Elasticssearch 5.0.0, which i'm not sure if that is right since thats in alpha currently.

Could be something I'm doing wrong, but not sure. Currently i'm running 2.3.4 for elasticsearch

**Comment by amartin916** [comment]
yes pulled it down, switch to that branch, ran npm install inside the directory... That might be where things went wrong.  doing that ended up creating node_modules/elasticsearch/index.js which is where that version conflict kicks up. 

So I'm guessing I built it wrong somehow.

**Comment by ppadovani** [comment]
Yeah... I'll have to go back and look at that branch.. please switch to the nestedSupport-4.4.1 branch.. I pushed a change that allows it to work against 1.7.X through 2.x.

I found that you'll have to clean out the previously installed dependencies to get it to build. I just removed the directory and re-cloned the repo, then switched to the branch.

Don't forget to run
 nvm install "$(cat .node-version)"   

before running npm install.

Tested against elasticsearch 2.2.1 and 1.7.0
