### ISSUE TITLE
Support for Nested Queries

### ISSUE THREAD

**Issue by jprabawa** [homeaway/kibana#10]
I'm testing your `nestedSupport-4.5.4` branch and its working fine so far except for nested queries.

So for example, lets say my index mapping is:
```
{
    "library": {
        "mappings": {
            "book": {
                "dynamic": "strict",
                "properties": {
                    "reviewer": {
                        "type": "nested",
                        "properties": {
                            "name": {
                                "type": "string",
                                "index": "analyzed",
                                "analyzer": "standard",
                                "fields": {
                                    "raw": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                    }
                                }
                            },
                            "country": {
                                "type": "string"
                            },
                            "age": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

If I create a Pie Chart with a Terms Aggregation on the field `reviewer.name.raw`, the visualization is shown correctly.

But when I click on one of the terms (one of the slices in the pie chart), for example where `reviewer.name.raw` is "John Doe", the resulting Kibana filter thats created is:

```
{
  "query": {
    "match": {
      "reviewer.name.raw": {
        "query": "John Doe",
        "type": "phrase"
      }
    }
  }
}
```

which is incorrect. To query the nested object, the filter should be:
```
{
  "query": {
	"nested": {
	  "path": "reviewer",
	  "query": {
		"match": {
		  "reviewer.name.raw": "John Doe"
		}  
	  }
	} 
  }
}
```

Info: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-nested-query.html

**Comment by ppadovani** [comment]
I have been unable to spend time on issues over the last few weeks. I will try and look at this and the other issue this week. Hopefully I will have a fix in place by early next week.

**Comment by jprabawa** [comment]
Thanks! Appreciate any time you can spend on this :)

**Comment by ppadovani** [comment]
Fixed and pushed.. please verify

**Comment by jprabawa** [comment]
Sorry for the late reply. 

Works like a charm. Many thanks! Closing bug :)
