### ISSUE TITLE
Viewing nested array of data in Discovery Tab

### ISSUE THREAD

**Issue by jprabawa** [homeaway/kibana#12]
Viewing nested data in the Discovery Tab works if whats nested is an object. 

If an array of objects are nested in the document, the Discovery Tab only shows data from the first item in the array.

For example, if the mapping is:

```
{
    "library": {
        "mappings": {
            "book": {
                "dynamic": "strict",
                "properties": {
                    "reviewer": {
                        "type": "nested",
                        "properties": {
                            "name": {
                                "type": "string",
                                "index": "analyzed",
                                "analyzer": "standard",
                                "fields": {
                                    "raw": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                    }
                                }
                            },
                            "country": {
                                "type": "string"
                            },
                            "age": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

And the document is:

```
{
    "reviewer": [
        {
            "name": "John Doe",
            "country": "US",
            "age": 23
        },
        {
            "name": "Jane Doe",
            "country": "GB",
            "age": 22
        }
    ]
}
```

Then the Discovery Tab will only show data for `"John Doe"` for the document.

**Comment by ppadovani** [comment]
This is a known issue, I just haven't had time to address it as my skills at angular are limited. I will leave this issue in place and try and work on this over the next few weeks.

**Comment by jprabawa** [comment]
Thanks! Just a small note for when and if you pick this up:

This issue might be more nuanced than I first thought because the Kibana UI allows users to promote any field name as a column header for the Documents table (see: https://www.elastic.co/guide/en/kibana/4.5/discover.html#adding-columns). 

So if we have a field name for every element in a nested array, then allowing users to elevate them as table columns would be quite weird. Not sure what the correct affordances should be here.

**Comment by ppadovani** [comment]
I had some time to look at this, and have something that seems to work... What do you think about this:
![image](https://cloud.githubusercontent.com/assets/11234684/23807775/960aaeea-058c-11e7-9fb3-9cbc105bde28.png)

**Comment by jprabawa** [comment]
Sorry for the late reply. That looks pretty good! Great work 👍. Does it scale to deeper nestings though? I have used mappings that are 3 levels deep (property -> array of objects -> object has an array property of some other object). Not sure how deep a nesting the UI should support though.

**Comment by ppadovani** [comment]
The changes are recursive, and will go as deep as the data... it may look odd as you dig down... I've got a several level deep mapping that we have internally, I'll see if I can get a screen cap of what that looks like. 

In terms of the 'add column' support button, I'm thinking that it should be disabled or not appear in the nested data set.

Thoughts?

Pierre

**Comment by ppadovani** [comment]
Ok.. have it working... the test data I am using is pretty large... so I have to show this in two screenshots..
One level:
![image](https://cloud.githubusercontent.com/assets/11234684/23863486/f0b73c34-07dd-11e7-9233-883683977e6a.png)

Second level:
![image](https://cloud.githubusercontent.com/assets/11234684/23863503/000ed3a4-07de-11e7-9d79-635422472b96.png)

The current iteration has an issue where when you open up one of the second level nested, all second level nested that are the same field get opened as well..something I will fix...

Overall this looks like it will work, however I'm thinking that given a list of nested objects would/should it make sense to have them pre-collapsed with a summary string like a normal row? 

I'll push this to the nestedSupport-5.2 branch and you can play with it if you'd like.

**Comment by jprabawa** [comment]
Wow that looks pretty promising!

Some thoughts:

I concur that the "Add column" button should be disabled for nested proprieties. Doesn't make much sense to enable it since nested properties don't behave like traditional columns especially when we have arrays of objects. 

Summaries for collapsed nested objects may or may not make sense depending on what's nested I guess. I can only think of three possible summaries: 

1. The full json of what's nested (which may break the UI when there's too much nested), or

2. A snippet of the json of what's nested (like the first 200 characters which may not be very useful; but query-aware snippets would be interesting)

3. Statistics (like number of nested properties if an object or number of items if it's an array)

The simplest and safest method would probably be the snippet method with the first k characters as a snippet. 

And yes, would love to pull from your branch and play around if it's not too much trouble for you to push your recent changes. I'll play around and try and catch anomalies if any :)

Thanks!

**Comment by ppadovani** [comment]
Pushed... 

I'll emulate the summary code that is currently used for overall hits and see how that looks/works.. I'll update here again with a screenshot when I have it working.

**Comment by ppadovani** [comment]
Ok.. check this out...

![image](https://cloud.githubusercontent.com/assets/11234684/23870467/79db5138-07f4-11e7-9224-97f909abdeb3.png)

I still have a bug around toggling I need to track down.. and I don't like how long some of the 'dotted' field names are... am thinking to truncate from the beginning for really long names...

thoughts?

**Comment by ppadovani** [comment]
pushed my changes with a toggle fix.

**Comment by jprabawa** [comment]
Was trying to load up the build when I realized that my data is still running on ES 2.3.4 :( 

I was using your `nestedSupport-4.5.4` branch for my ES version. May need to have the changes in that branch if you want me to play around with it :( Sorry!

On the summary, they look good except for the html encoding though. e.g. its probably more useful if the quotes come out as `"` instead of `&quot;`. I think the data was probably encoded twice. `"` -> `&quot;` -> `&amp;&quot;`. The html source can confirm if this is the case.

On the long field names, since the nested properties will always have a common prefix with their parents, might make sense to remove the common prefix. This would alleviate the issue somewhat. So in your case, the common prefix would be `unitMetaDatas` which will be removed in this design.

**Comment by ppadovani** [comment]
I can back port to that version. Let me fix the names first and the html encoding. Performance is also an issue with the way I implemented it, so I want to fix that as well.

**Comment by jprabawa** [comment]
Awesome. Thanks :D

**Comment by ppadovani** [comment]
ok.. I ported it to all of my supported versions. Officially it was a PITA. Patching back and forth in 5.x is easy, going back to 4.7/6 required hand patching the code. Going from 4.6 to 4.5.4 also required some hand patching.

There are some layout differences between 5.x and 4.x due to the CSS differences. I didn't want to mess with things too much. If anything stands out that should be fixed, let me know.

**Comment by jprabawa** [comment]
Really sorry about that :( I would have been fine to not have this in your v4.5.4 branch actually. I just meant that I cant help you test it out since Im using ES 2.3.4. Anyway thanks very much. 

About the build:

1. The layout has some trivial oddities (column sizes and alignments change when opening and closing the nested data)  but I think they're fine as-is.

2. I noticed that the field name shortening is not applied if that field opens up to reveal another layer. Not sure if this was intentional:

Following your example in https://github.com/homeaway/kibana/issues/12#issuecomment-286157918, the new build would have displayed the structure as:

- `paymentPlanMetaDatas_size`
- ...
- `unitMetaDatas`
    - `srcEntityUpdated`
    - ...
    - `unitMetaDatas.unitDistributionEligibilities`
        - `distributionAdvertiserConfiguration`
        - ...

So should the second nesting above be displayed instead as `unitDistributionEligibilities` and not `unitMetaDatas.unitDistributionEligibilities`?

Other than that, I think this works pretty well.

**Comment by ppadovani** [comment]
Yeah the field name shortening on the fields that open up... that is a bug... I'll fix it today and push out these changes across the branches. I may try and see if I can at least get the layout more consistent as well if I have time.

Thanks for the feedback!

**Comment by ppadovani** [comment]
Who said you couldn't teach an old dog new tricks... I'm not a UI person, but I learned something new... layout issues are fixed, and the truncation as well.

Pushed to nestedSupport-4.5.4

**Comment by ppadovani** [comment]
Pushed the changes to all branches. I'm going to close this, please re-open if you spot any other issues.

**Comment by jprabawa** [comment]
Awesome! Thanks!
