### ISSUE TITLE
Support for Ordering Nested Aggregations by Reverse Nested Aggregation

### ISSUE THREAD

**Issue by jprabawa** [homeaway/kibana#13]
By default, nested aggregations are ordered by the count of the nested documents. For nested arrays of data, the aggregation metric may instead, need to be the count of the root documents (for semantic reasons).

For example, in the mapping:

```
{
    "library": {
        "mappings": {
            "book": {
                "dynamic": "strict",
                "properties": {
                    "title": {
                        "type": "string",
                        "index": "analyzed",
                        "analyzer": "standard",
                        "fields": {
                            "raw": {
                                "type": "string",
                                "index": "not_analyzed"
                            }
                        }
                    },
                    "reviewer": {
                        "type": "nested",
                        "properties": {
                            "name": {
                                "type": "string",
                                "index": "analyzed",
                                "analyzer": "standard",
                                "fields": {
                                    "raw": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                    }
                                }
                            },
                            "country": {
                                "type": "string"
                            },
                            "age": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

A query for a nested aggregation on `reviewer.country` would be:

```
{
  "aggs": {
    "reviewer": {
      "nested": {
        "path": "reviewer"
      },
      "aggs": {
        "country": {
          "terms": {
            "field": "reviewer.country",
            "size": 10,
            "order": {
              "_count": "desc"
            }
          }
        }
      }
    }
  }
}
```

But this gives us, for each country, the count of reviewers (the nested document). But If we wanted to count the number of books (the root document), then the query should be:

```
{
  "aggs": {
    "reviewer": {
      "nested": {
        "path": "reviewer"
      },
      "aggs": {
        "country": {
          "terms": {
            "field": "reviewer.country",
            "size": 10,
            "order": {
              "book": "desc"
            }
          },
          "aggs": {
            "book": {
              "reverse_nested": {}
            }
          }
        }
      }
    }
  }
}
```

In the Kibana UI, the `Order By` field lets users order by a `Custom Metric`. Of the different Aggregation types there, the `Unique Count` Aggregation should give us what we want, but the resulting query is wrong as it does not nest the field inside a `reverse_nested` aggregation first.

For example, continuing the above example, if we are to `Order By` on a `Unique Count` on `title`, the query would be:

```
{
  "size": 0,
  "query": {
    "query_string": {
      "query": "*",
      "analyze_wildcard": true
    }
  },
  "aggs": {
    "nested_2": {
      "nested": {
        "path": "reviewer"
      },
      "aggs": {
        "2": {
          "terms": {
            "field": "reviewer.country",
            "size": 10,
            "order": {
              "2-orderAgg": "desc"
            }
          },
          "aggs": {
            "2-orderAgg": {
              "cardinality": {
                "field": "title"
              }
            }
          }
        }
      }
    }
  }
}
```

But the correct query should be:

```
{
  "size": 0,
  "query": {
    "query_string": {
      "query": "*",
      "analyze_wildcard": true
    }
  },
  "aggs": {
    "nested_2": {
      "nested": {
        "path": "reviewer"
      },
      "aggs": {
        "2": {
          "terms": {
            "field": "reviewer.country",
            "size": 10,
            "order": {
              "2-reverseNested>2-orderAgg": "desc"
            }
          },
          "aggs": {
            "2-reverseNested": {
              "reverse_nested": { }, 
              "aggs": {
                "2-orderAgg": {
                  "cardinality": {
                    "field": "title"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Note that ideally we should not need to do a unique count on a root document field if all we wanted is to count the number of root documents.

**Comment by ppadovani** [comment]
I'll take a look at this over the next few days.

**Comment by jprabawa** [comment]
Thanks! Apologies for the barrage of reports :)

**Comment by ppadovani** [comment]
No worries on the barrage of reports... just means people are starting to use this. :-)

**Comment by jprabawa** [comment]
Any updates on this? :)

**Comment by ppadovani** [comment]
Thanks for the ping. Life got in the way. :-) I will look at this over the next few days.

**Comment by ppadovani** [comment]
I played with this a bit in the UI, and the aggregations via curl... The two issues you point out here, will have to be addressed individually.

1-Count of parent rather than nested. I can see the need for selecting which of the two is required. I believe that having the drop down that allows the user to select the order by, should be a bit more dynamic. If the user has selected a nested field, the 'metric: Count' should be replaced with two possible options: 'metric: Count documents' and 'metric: Count nested'. The latter would function as it does currently, the former would induce the behavior you have provided above.

2- The order based on a parent field aggregation. This one is really just a back end code change to be smarter about the aggregation generation, and of the two is likely the easier to deal with as it doesn't require an UI work.

**Comment by jprabawa** [comment]
Sounds about right. 

If Issue 2, as you described, is solved, then the existing UI can be used to count as well as order by the number of root documents by creating a `Custom Metric` on a root document field.

**Comment by ppadovani** [comment]
I believe this is now fixed in the nestedSupport-4.5.4 branch.

Please retest.

**Comment by jprabawa** [comment]
Thanks for your help on this :) 

I just tested and the ES query is now correct but for some reason, kibana is still reporting the nested doc values. Im not sure if this is a UI-issue or one with the response parsing.

In the example above, the correct query is issued:

```
{
  "size": 0,
  "query": {
    "query_string": {
      "query": "*",
      "analyze_wildcard": true
    }
  },
  "aggs": {
    "nested_2": {
      "nested": {
        "path": "reviewer"
      },
      "aggs": {
        "2": {
          "terms": {
            "field": "reviewer.country",
            "size": 10,
            "order": {
              "nested_2-orderAgg>2-orderAgg": "desc"
            }
          },
          "aggs": {
            "nested_2-orderAgg": {
              "reverse_nested": { }, 
              "aggs": {
                "2-orderAgg": {
                  "cardinality": {
                    "field": "title"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

And in the response, for example, we would get something like:
```
{
  "took": 173,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 79244,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "nested_2": {
      "2": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [
          {
            "key": "SG",
            "doc_count": 124086,
            "nested_2-orderAgg": {
              "doc_count": 67518,
              "2-orderAgg": {
                "value": 68318
              }
            }
          },
          {
            "key": "US",
            "doc_count": 42940,
            "nested_2-orderAgg": {
              "doc_count": 40057,
              "2-orderAgg": {
                "value": 38945
              }
            }
          },
          {
            "key": "NIL",
            "doc_count": 81,
            "nested_2-orderAgg": {
              "doc_count": 79,
              "2-orderAgg": {
                "value": 79
              }
            }
          }
        ]
      },
      "doc_count": 167107
    }
  }
}
```

In the UI, the numbers displayed for the terms are taken from `doc_count`, so `124086`, `42940`, and `81`; instead of from `nested_2-orderAgg>2-orderAgg` i.e. `68318`, `38945`, and `79`.

**Comment by ppadovani** [comment]
So... order is different than count... I believe the order problem is resolved.. however I do see what you mean about count... As I see it there are two ways to count in a nested index ... 

- count of nested objects
- count of parent documents

Do we always count the parent in Kibana? Is there a valid use case for also being able to count the nested objects? I should be able to fix the parent document count by adding another aggregation by adding an empty reverse_nested aggregation, per this: http://stackoverflow.com/questions/33040665/elasticsearch-aggregate-nested-fields-as-part-of-parent-document

But... should that always be the case?

**Comment by jprabawa** [comment]
Ah! I'm so sorry. You are right. I just checked the normal behaviour of Kibana and changing the `Order By` does not change the count that is displayed. My bad. The latter is instead controlled by the `Aggregation` settings under the `metrics` tab. 

Like the `Order By` settings, the UI lets us select `Unique Count` in the `Aggregation` settings, where we can select a custom field to count.

So following the example so far, if we try to do a unique count on `title`, the query produced is:
```
{
  "size": 0,
  "query": {
    "query_string": {
      "query": "*",
      "analyze_wildcard": true
    }
  },
  "aggs": {
    "nested_2": {
      "nested": {
        "path": "reviewer"
      },
      "aggs": {
        "2": {
          "terms": {
            "field": "reviewer.country",
            "size": 5,
            "order": {
              "1": "desc"
            }
          },
          "aggs": {
            "1": {
              "cardinality": {
                "field": "title"
              }
            },
            "nested_1": {
              "reverse_nested": {},
              "aggs": {
                "1": {
                  "cardinality": {
                    "field": "title"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Which is incorrect because when we use a custom field aggregation as the count, the `Order By` selection of `metric: Count` also changes accordingly. In our case, the UI changed it to `metric: Unique count of title`. This means that:

1. The `order` key in the query should be using `nested_1>1` instead of `1`

2. The aggregation `1` might be unnecessary

The response to the query above is the following:

```
{
  "took": 48,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 79244,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "nested_2": {
      "2": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [
          {
            "1": {
              "value": 0
            },
            "key": "US",
            "doc_count": 42940,
            "nested_1": {
              "1": {
                "value": 38945
              },
              "doc_count": 40057
            }
          },
          {
            "1": {
              "value": 0
            },
            "key": "NIL",
            "doc_count": 81,
            "nested_1": {
              "1": {
                "value": 79
              },
              "doc_count": 79
            }
          },
          {
            "1": {
              "value": 0
            },
            "key": "SG",
            "doc_count": 124086,
            "nested_1": {
              "1": {
                "value": 68318
              },
              "doc_count": 67518
            }
          }
        ]
      },
      "doc_count": 167107
    }
  }
}
```

With this response, Kibana is displaying the count from the aggregation `1`, which is all `0`, so no graph is displayed and an error message appears: `No results displayed because all values equal 0`.

Regarding your question, I believe both use cases are valid and really depends on the domain of the entities being indexed. To really solve these use cases out-of-the-box, as you suggested, we will need to change the UI to give an option of `metric: Count documents` and `metric: Count nested`. We can think of this as a feature and not a bug-fix though.

However, the queries generated using custom `Order By` on a parent field should not be wrong if the term aggregation is on a nested field (which you have fixed! thanks :D). 

Now it seems that the queries generated using a custom `Unique Count` `Aggregation` on a parent field is also similarly incorrect if the term aggregation is on a nested field.

**Comment by ppadovani** [comment]
So here is what I'm thinking... I update the UI as follows:
![image](https://cloud.githubusercontent.com/assets/11234684/20601576/f166c40c-b21e-11e6-8ced-8a01acf66772.png)

The 'Count By' only shows up if you have selected a nested field. If 'parent document' is selected, an empty reverse_nested aggregation will be injected and used for the count. If 'child object' is selected, nothing will be injected and it will be have as it does today..

I could use a checkbox as well...

**Comment by jprabawa** [comment]
Your suggestion is actually much better for my use case. Because all I really want is to count and order by the root document. 

Keep in mind though that when the user selects a custom aggregation as the count, as I described earlier, the bug will still be there.

**Comment by ppadovani** [comment]
Ok... I believe I have what you are looking for.. it is pushed... the UI change is simple:
![image](https://cloud.githubusercontent.com/assets/11234684/20695478/ed46e514-b5b1-11e6-9917-abf0284ac98e.png)

Which will generate something like:
` "aggs": {
    "nested_2": {
      "nested": {
        "path": "cars"
      },
      "aggs": {
        "2": {
          "terms": {
            "field": "cars.make",
            "size": 5,
            "order": {
              "_count": "desc"
            }
          },
          "aggs": {
            "count_2": {
              "reverse_nested": {}
            }
          }
        }
      }
    }`

Internally if a sub-agg has an id of 'count_' + the id of the parent, then that count is used instead.

Let me know if this resolves this issue.

**Comment by jprabawa** [comment]
Thanks! This does solve my issue on counting and displaying by number of parent documents :D 

However, there seems to be a bug when used together with the bug-fix for ordering by a parent field.

I need both solutions to work for my use-case because counting and displaying based on the number of parent documents makes more sense if we are also ordering by it. Otherwise, Top-k visualisations will be incorrect.

Using your car domain example, the query generated when the checkbox of `Use count of parent document` is ticked, is correct:

```
{
  "query": {
    "query_string": {
      "query": "*",
      "analyze_wildcard": true
    }
  },
  "size": 0,
  "aggs": {
    "nested_2": {
      "nested": {
        "path": "cars"
      },
      "aggs": {
        "2": {
          "terms": {
            "field": "cars.make",
            "size": 5,
            "order": {
              "_count": "desc"
            }
          },
          "aggs": {
            "count_2": {
              "reverse_nested": {}
            }
          }
        }
      }
    }
  }
}
```

But when I changed the `Order By` to use a `Custom Metric` of a `Unique Count` `Aggregation` on a unique parent field, e.g. `House Address` so that I can simulate ordering by number of parent documents, I get this query:

```
{
  "query": {
    "query_string": {
      "query": "*",
      "analyze_wildcard": true
    }
  },
  "size": 0,
  "aggs": {
    "nested_2": {
      "nested": {
        "path": "cars"
      },
      "aggs": {
        "2": {
          "terms": {
            "field": "cars.make",
            "size": 5,
            "order": {
              "nested_2-orderAgg>2-orderAgg": "desc"
            }
          },
          "aggs": {
            "count_2": {
              "reverse_nested": {}
            }
          }
        }
      }
    }
  }
}
```

which fails because there is no path `nested_2-orderAgg>2-orderAgg` in the query.

The error message is: `Invalid term-aggregator order path [nested_2-orderAgg>2-orderAgg]. Unknown aggregation [nested_2-orderAgg]`

The query that gets produced with the `Custom Metric` without the `Use count of parent document` ticked, is:

```
{
  "query": {
    "query_string": {
      "query": "*",
      "analyze_wildcard": true
    }
  },
  "size": 0,
  "aggs": {
    "nested_2": {
      "nested": {
        "path": "cars"
      },
      "aggs": {
        "2": {
          "terms": {
            "field": "cars.make",
            "size": 5,
            "order": {
              "nested_2-orderAgg>2-orderAgg": "desc"
            }
          },
          "aggs": {
            "nested_2-orderAgg": {
              "reverse_nested": {},
              "aggs": {
                "2-orderAgg": {
                  "cardinality": {
                    "field": "address"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by ppadovani** [comment]
ok.. Sorry about that.. was a bit tired when I finished that up... I just pushed a fix, that I verified. Please re-test.

**Comment by jprabawa** [comment]
Works perfectly now :D Thanks so so much!! Closing the issue
