### ISSUE TITLE
Kibana 5.0

### ISSUE THREAD

**Issue by Aludirk** [homeaway/kibana#16]
Is any plan to support the most updated kibana 5.0 ?
We will appreciate to have that.

**Comment by ppadovani** [comment]
Yes... I intend to start sometime in the next week or two...

**Comment by ppadovani** [comment]
I've created the branch and will begin work on it this week.

**Comment by ppadovani** [comment]
Just took a look at existing 5.X functionality... aggregations using nested objects is fully supported, as long as you only care about the counts of the parent document. What is missing is calculating the counts of the nested objects... This will require some thought on how to properly shim in changes to properly support metrics/counts of nested objects.

**Comment by ppadovani** [comment]
I'm going to port to 4.6 and 4.7 first... then it will be easier to port to 5.0

**Comment by ppadovani** [comment]
4.6 and 4.7 are done. I have most of the 5.0 code ported.. then discovered that within Elasticsearch 5.X, the get mapping REST interface no longer returns any nested information. This puts a hold on this port until I get an answer back from elastic. This is a problem not just for this fork, but for anyone who uses nested objects and wants to 'copy' a mapping from one cluster to another, or even verify that the mapping on the cluster matches the original mapping used to create the index.

**Comment by ppadovani** [comment]
done and pushed
