### ISSUE TITLE
All fields become non indexed fields

### ISSUE THREAD

**Issue by Aludirk** [homeaway/kibana#2]
I installed the nestedSupport-4.4.1 branch with 
```bash
nvm install "$(cat .node-version)"
npm install
```

Every time I added a new or refresh the index pattern, all fields become non-indexed except "non-analyzed string" type.

If I switch back to official kibana (4.5.3) which connect to the same elasticesearch, and then create/refresh an index pattern, all fields changed back to indexed.

My elasticsearch is 2.3.4

A simple index with following mappings can be reproduced:
```json
PUT test
{
  "mappings": {
    "test": {
      "properties": {
        "s": {
          "type": "string",
          "index": "not_analyzed"
        },
        "i": {
          "type": "integer"
        }
      }
    }
  }
}
```

**Comment by ppadovani** [comment]
I'll take a look at this over the next day or so.

**Comment by ppadovani** [comment]
Please re-pull the 4.4.1 branch and try again.. I pushed a small fix that I think will resolve the issue.

I will also be looking at rebasing my changes onto the latest Kibana release.

**Comment by ppadovani** [comment]
There is now a nestedSupport-4.5.4 branch that works as well.

**Comment by ppadovani** [comment]
Can you re-test this please?

**Comment by Aludirk** [comment]
Sorry for late reply
I used nestedSupport-4.5.4 for testing
All fields are indexed now, but when I compared with the official one, some meta fields such as _id, _index etc. should not be indexed, and I found that all analyzed fields are lost

**Comment by ppadovani** [comment]
Ok... I see what is wrong.. I made an invalid assumption about how an elasticsearch api worked... I'll need to code up a workaround.

**Comment by ppadovani** [comment]
Ok.. I believe this is fixed, please retest.

**Comment by Aludirk** [comment]
The index/analyzed problem is fixed, thx.

I got a new observation, but I'm not sure whether should I open a new issue, anyway I just write down here first.

For the `geo_point` type, I can config two parameters `geohash` and `lat_lon`, and both are false as default.  When I try the following mappings:
```
PUT /test
{
  "mappings": {
    "test": {
      "properties": {
        "location": {
          "type": "geo_point",
          "lat_lon": true,
          "geohash": true
        }
      }
    }
  }
}
```

It seems that Elasticsearch will inject some new fields.

For `lat_lon`:
- `location.lat` (type:number indexed:true)
- `location.lon` (type:number indexed:true)

For `geohash`:
- `location.geohash` (type:string analyzed:false indexed:true)

But this time those three fields are all missing.

**Comment by ppadovani** [comment]
Ok.. pretty sure this is fixed now.. please re-test

**Comment by Aludirk** [comment]
It's ok now, thank you very much.
