### ISSUE TITLE
Upgrade Kibana to 5.1.1

### ISSUE THREAD

**Issue by Hronom** [homeaway/kibana#20]
Please upgrade Kibana in branch with 5.x support to 5.1.1, currently it 5.0.2

**Comment by ppadovani** [comment]
Yep, been on vacation will get to it in the next few days.

**Comment by Hronom** [comment]
Thanks in advance!

**Comment by ppadovani** [comment]
done: https://github.com/homeaway/kibana/tree/nestedSupport-5.1
