### ISSUE TITLE
Metric with Unique Count not work

### ISSUE THREAD

**Issue by Hronom** [homeaway/kibana#21]
`Metric` visualization with `Unique Count` not work with nested objects, here is the code for creating test index:

```
PUT /test-index-no
{
    "settings": {
        "number_of_shards": 1
    },
    "mappings": {
        "planet": {
            "properties": {
                "name": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "humans": {
                    "type": "nested",
                    "properties": {
                        "firstName": {
                            "type": "string",
                            "index": "not_analyzed"
                        },
                        "lastName": {
                            "type": "string",
                            "index": "not_analyzed"
                        }
                    }
                }
            }
        }
    }
}
```

```
POST /test-index-no/planet/
{
   "name": "Earth",
   "humans": [
      {
         "firstName": "Keanu",
         "lastName": "Reeves"
      },
      {
         "firstName": "Laurence",
         "lastName": "Fishburne"
      }
   ]
}
```

```
POST /test-index-no/planet/
{
   "name": "DC Earth",
   "humans": [
      {
         "firstName": "Batman",
         "lastName": ""
      },
      {
         "firstName": "Superman",
         "lastName": ""
      }
   ]
}
```

Try create `Metric` with aggregation `Unique Count` for fields `humans.firstName` and `humans.lastName`.

But if you use field `name` it works.

![1](https://cloud.githubusercontent.com/assets/429993/21524053/d82c337e-cd1b-11e6-8a39-591bff17e705.png)
![2](https://cloud.githubusercontent.com/assets/429993/21524052/d8284f2a-cd1b-11e6-8c5f-afa3b8c16796.png)

**Comment by ppadovani** [comment]
Been on vacation, will take a look in the next few days.

**Comment by ppadovani** [comment]
Once I fix this in 5.1 I'll back port to all supported versions I have.

**Comment by ppadovani** [comment]
The generated request is correct:
`{
  "size": 0,
  "query": {
    "query_string": {
      "query": "*",
      "analyze_wildcard": true
    }
  },
  "_source": {
    "excludes": []
  },
  "aggs": {
    "nested_1": {
      "nested": {
        "path": "humans"
      },
      "aggs": {
        "1": {
          "cardinality": {
            "field": "humans.firstName"
          }
        }
      }
    }
  }
}`

Reading up on cardinality aggregations, this may be an issue with how it deals with nested data and precision_threshold. Is there a way that you can get the correct data back by hand forming the aggregation query?

**Comment by Hronom** [comment]
@ppadovani I have tried next request:
```
POST /test-index-no/planet/_search
{
  "size": 0,
  "query": {
    "query_string": {
      "query": "*",
      "analyze_wildcard": true
    }
  },
  "_source": {
    "excludes": []
  },
  "aggs": {
    "nested_1": {
      "nested": {
        "path": "humans"
      },
      "aggs": {
        "1": {
          "cardinality": {
            "field": "humans.firstName"
          }
        }
      }
    }
  }
}
```
and got next:
```
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "nested_1": {
      "1": {
        "value": 4
      },
      "doc_count": 4
    }
  }
}
```
So seems like in response valid value: `4`, so why there is no result in metric widget?

**Comment by ppadovani** [comment]
Alright, I believe I have it resolved.. please validate.

**Comment by Hronom** [comment]
Tested branch nestedSupport-5.1 and it's works, big thanks!
