### ISSUE TITLE
top query field does not work as in original Kibana

### ISSUE THREAD

**Issue by debdude** [homeaway/kibana#22]
**Kibana version**: 4.6 -5.1

**Browser version**: Chrome OS X

**Original install method (e.g. download page, yum, from source, etc.)**: zip dl

**Description of the problem including expected versus actual behavior**: In original Kibana, query field in 'Discover' tab works with free text input and searches all fields by default. In all -nestedSupport forks I tried (4.6-5.1), it requires more formal syntax "field:search pattern" and gives an error otherwise

![screen shot 2017-01-23 at 00 52 39](https://cloud.githubusercontent.com/assets/3797695/22186446/1a17d3b6-e107-11e6-92f3-7cd043ae8d6f.png)

**Comment by ppadovani** [comment]
I will fix this shortly. Sorry for not looking at this sooner...

**Comment by ppadovani** [comment]
So, the way my code differentiates between what type of query you are using is based on a regex that tries to match a lucene style query versus a query style in our simplified language. I think I'm going to have to change this to something the user selects near the query bar...

**Comment by ppadovani** [comment]
Ok.. How about something like this... I add a toggle to the right hand side of the query bar:
Default:
![image](https://cloud.githubusercontent.com/assets/11234684/22896628/799aaeea-f1e6-11e6-8c6a-73764b7def12.png)

Oposite state:
![image](https://cloud.githubusercontent.com/assets/11234684/22896653/8f626416-f1e6-11e6-88b0-0ad87a4fa831.png)

This will avoid the auto detection problem, and instead rely on the user to choose the query language they wish to use.

**Comment by debdude** [comment]
such a switch would be awesome, cool!

**Comment by ppadovani** [comment]
ok.. I'll get something running on 5.1 in the next few days.

**Comment by ppadovani** [comment]
I pushed this enhancement to the nestedSupport-5.1 branch.. please take a look. If it looks good, I'll back-port to the other branches.

**Comment by ppadovani** [comment]
Closing, the toggle provides the needed workaround, and has been back ported.
