### ISSUE TITLE
SUM aggregation does not work while AVERAGE, etc. work as expected

### ISSUE THREAD

**Issue by debdude** [homeaway/kibana#23]
**Kibana version**: -nestedSupport 4.6

**Elasticsearch version**: 2.4

**Original install method (e.g. download page, yum, from source, etc.)**: zip dl

Trying to get a sum of nested object values, sum does not work even though correct json is returned. Other functions such as Average work as expected.

I have this mapping for a person:
`person_mapping = {
   "mappings": {
      "person": {
         "properties": {
            "accounts": {
               "type": "nested",
               "properties": {
                  "bank_name": {
                     "type": "string"
                  },
                  "currency": {
                     "type": "string"
                  },
                  "amount": {
                     "type": "long"
                  }
               }
            }
         }
      }
   }
}`

![screen shot 2017-01-23 at 01 11 56](https://cloud.githubusercontent.com/assets/3797695/22186608/33f25c64-e109-11e6-9e4f-dae98175285d.png)
![screen shot 2017-01-23 at 01 12 14](https://cloud.githubusercontent.com/assets/3797695/22186609/33f3cde2-e109-11e6-9597-93b279e8ec65.png)

**Comment by ppadovani** [comment]
I'll take a look at this in the next couple of days.

**Comment by ppadovani** [comment]
Can you do a quick pull and retest? I backported a fix that I made for metrics in 5.1 ...

**Comment by debdude** [comment]
thanks, I'll retest first thing tomorrow!

**Comment by ppadovani** [comment]
Any update on testing this?

**Comment by ppadovani** [comment]
please re-open if this is still an issue.
