### ISSUE TITLE
Wildcard search in discovery tab isn't working

### ISSUE THREAD

**Issue by Tehtehteh** [homeaway/kibana#28]
**Kibana version**: 4.7

**Elasticsearch version**: 2.4.0

**Server OS version**: Ubuntu

**Browser version**: Chrome

**Original install method (e.g. download page, yum, from source, etc.)**: from [source](https://github.com/homeaway/kibana/tree/nestedSupport-4.7)

**Description of the problem including expected versus actual behavior**:
Wildcard queries for nested properties are not working as expected. Tried old kibana query syntax thru switch in discovery panel.
For example, if we have nested "users" property in our index and "name" in this nested property and we want to query all users with name starting with "test*" ("test1", "test2", "test3"..etc) in old Kibana we use this query:
`name: test*` (expecting each user has it's own document opposite to nested solution)
And in this fork version I tried multiple queries:
`users.name="test1"` - this will yield all documents with specific user name. Looks correct, but without wildcard. However
`users.name:"test*"` yields no results.

**Comment by ppadovani** [comment]
Thanks for the report. I just got back in town, I'll try and take a look at this in the next few days.

**Comment by ppadovani** [comment]
Sorry for the delay on this, work and life.

I will be able to spend time fixing this next week.

**Comment by ppadovani** [comment]
Moved this issue here to the new plugin: [#18](https://github.com/ppadovani/KibanaNestedSupportPlugin/issues/18)
