### ISSUE TITLE
Reverse nested for referencing another nested doc

### ISSUE THREAD

**Issue by takamuffin** [homeaway/kibana#9]
I would like the ability to use reverse_nested in the case of aggregating another nested doc of the same type, but with differing keys.

Sample document:

```
{
  "shirt": [{
    "color": "red",
    "size": "medium",
    "cotton": "egyptian"
  }, {
    "color": "blue",
    "size": "large",
    "polyester": "synthetic"
  }]
}
```

The query that is necessary to achieve this (I'm aware it doesn't make sense in this example):
```
{
   "size": 0,
   "query": {
      "match_all": {}
   },
   "aggs": {
      "shirts": {
         "nested": {
            "path": "shirt"
         },
         "aggs": {
            "cotton": {
               "terms": {
                  "field": "shirt.cotton"
               },
               "aggs": {
                  "other_shirts": {
                     "reverse_nested": {},
                     "aggs": {
                        "polyester": {
                           "terms": {
                              "field": "shirt.polyester"
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}
```

The following is what is produced by the aggregation builder:
```
{
   "size": 0,
   "query": {
      "match_all": {}
   },
   "aggs": `{`
      "shirts": {
         "nested": {
            "path": "shirt"
         },
         "aggs": {
            "cotton": {
               "terms": {
                  "field": "shirt.cotton"
               },
               "aggs": {
                  "polyester": {
                     "terms": {
                        "field": "shirt.polyester"
                     }
                  }
               }
            }
         }
      }
   }
}
```

**Comment by ppadovani** [comment]
Sounds like an edge case that I missed... I'll take a look at it sometime in the next few days.

Thanks for the report!

**Comment by ppadovani** [comment]
I'm just now getting a chance to look at this... the aggregation code for handling nested queries depends on the path... in that it uses it as a clue to know when to combine queries in the same nested block, add another nested block, or use reverse nested. 

In the example you have provided your documents have the same nested path, and therefore the aggregations will always be combined in the same nested block. I don't believe there is a way to automatically implement your desired behavior. What we could do is add the ability for the user to add a '{"reverse_nested" : {}}' string to the JSON input in the advanced section of the aggregation. I could write code that intercepts that custom json block and updates the aggregation.

Let me know your thoughts

**Comment by takamuffin** [comment]
I have actually completely re-architected my data to use parent-child now (among other changes and enhancements)

If you would like to spend the time to add this feature, then I would say adding a small tweak that allows the user to control when "reverse_nested" is added to the aggregation would be a sufficient step. Especially since what you have so far works in pretty much all the other cases I attempted. 

I would say to wait until someone else encounters this same need, however.
